name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy v3frankie.me
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.13.0
        

        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./dist --project-name=v3frankie-me
          packageManager: pnpm
